### ISSUE TITLE
make program generative

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hot-summit#15]
ala OSMGeoWeek, make the program generative from _posts/program (which does not exist yet)

**Comment by bgirardot** [comment]
I am not sure this is worth it for a 5 or 6 page brochure type site like we have. They had a lot more content with mapping guides and such.

**Comment by mikelmaron** [comment]
We had 33 events in OSMGeoWeek and this helped a lot and wasn't too hard to implement. How many sessions do we expect at the hot summit?

**Comment by bgirardot** [comment]
Oh I don't know how many sessions, back of the envelope says about 13 or 14 at the most I would guess. Do you think we will need website content for every session?

**Comment by danbjoseph** [comment]
- it's already setup this way from #16 
- however, if we want links to pages for the individual events with  a little bit more info than the main program page (extended description, speaker, etc.) then the program/index.html needs to have the <a> tags around the title un-commented out and the _layouts/event.html needs to be adjusted for the hot summit and the *.md files in _posts/program/ need to be filled out with the additional info
