### ISSUE TITLE
set up recommendations@hotosm.org

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/hot-summit#28]
referenced on scholarship page

**Comment by bgirardot** [comment]
There is a scholarship email group, maybe we could just use that one for recommendations too?

**Comment by mikelmaron** [comment]
Do it! Makes sense \* Mikel Maron * +14152835207 @mikel s:mikelmaron 

```
 On Tuesday, February 17, 2015 8:20 PM, bgirardot <notifications@github.com> wrote:
```

 There is a scholarship email group, maybe we could just use that one for recommendations too?—

**Comment by bgirardot** [comment]
I think this is still a good idea to just use the scholarship email group but it will have to wait for configuration. This will have to be one of those allow public to post, but not see anything google groups. I have sent an email to accounts@hotosm and the scholarship email group to get it configured (actually to just include me in the manager role so I can configure it) as soon as that is done I think we are set to go.
