### ISSUE TITLE
Add Proposal Formats to the Submit a Proposal Page

### ISSUE THREAD

**Issue by wonderchook** [hotosm/hot-summit#32]
Right now you have to go to the form to see the types of proposals. Can we add that to the proposal page?

http://summit.hotosm.org/talk/

 Lightning talk (5 minutes)
 Presentation (20 minutes)
 Panel (1 hour)
 Workshop (2-4 hours)
 Other:

**Comment by bgirardot** [comment]
I can look at adding this.

**Comment by bgirardot** [comment]
@wonderchook I updated the propose a talk page, please let me know if it is not what you had in mind.
