### ISSUE TITLE
twitter hashtag?

### ISSUE THREAD

**Issue by danbjoseph** [hotosm/hot-summit#4]
osmgeoweek site has a link in the top nav bar that takes you to a search on twitter for hashtag osmgeoweek. do we want to have a hashtag we encourage people to use for the summit?

**Comment by mikelmaron** [comment]
Sure, what not #hotsummit \* Mikel Maron * +14152835207 @mikel s:mikelmaron 

```
 On Friday, February 13, 2015 6:27 PM, Dan Joseph <notifications@github.com> wrote:
```

 osmgeoweek site has a link in the top nav bar that takes you to a search on twitter for hashtag osmgeoweek. do we want to have a hashtag we encourage people to use for the summit?—
